@echo off
echo Starting Dora daemon...
start /B cmd /c "dora up"

echo Waiting for daemon...
timeout /t 5 /nobreak >nul

echo Building multi-view capture with MuJoCo visualization...
dora build dataflow_gen72_mujoco.yml

echo Starting dataflow...
dora start dataflow_gen72_mujoco.yml
